added restart article
JunimoHost/junimohost-docs pull request #2
Opened 2024-01-30 01:13 UTC by Samdaman8

2024-01-30 01:14 UTC, Samdaman8 commented
Current dependencies on/for this PR:
* `master`
  * **PR #2** <a href="https://app.graphite.dev/github/pr/JunimoHost/junimohost-docs/2?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/JunimoHost/junimohost-docs/2?utm_source=stack-comment).

2024-01-30 09:05 UTC, mrthinger requested changes
overall should be much more concise. these are not ads. these are docs aimed at existing customers.

2024-01-30 09:05 UTC, mrthinger commented on docs/issues-with-!events.md
remove ! from the filename. its actually breaking the site generation 😆 

![Added via Giphy](https://media2.giphy.com/media/cDWatyB6sfDQi1rivg/giphy.gif?cid=c9487743yssyzbpvoezt6lbhbpzg67knibnxa009y3xirr1k&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2024-01-30 09:05 UTC, mrthinger commented on docs/issues-with-!events.md
> +Attention to all our valued users, we've noticed some of you encountering issues when trying to start an event.
We dont need to do this. This makes the article less useful because it makes the useful part harder to find.

We're not making an announcement lol.![Added via Giphy](https://media1.giphy.com/media/2A5zHrIPvo8MNnkAXl/giphy.gif?cid=c9487743ece9tlxzi15xf32q28z8eue61twkljmzzy9os1qa&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2024-01-30 09:05 UTC, mrthinger commented on docs/issues-with-!events.md
> +We would like to stress the importance of typing the command **!event** only once. Please refrain from entering this command multiple times. Entering **!event** repeatedly could potentially lead to a
this makes it sound like its their fault. its our fault, we're working on fixing it, but here is a workaround for now

2024-01-30 09:05 UTC, mrthinger commented on docs/issues-with-!events.md
> +We understand this might cause some inconvenience and are putting measures in place to prevent such occurrences. In the meantime, we appreciate your understanding and cooperation in only entering the
more concise, we dont need to be coming off like a heartless corporation.

2024-01-30 09:05 UTC, mrthinger commented on docs/issues-with-!events.md
> +Thank you for choosing Junimohost for your Stardew Valley multiplayer experience. Happy Farming!
redundant. this is a help doc, not an ad.

2024-01-30 09:05 UTC, mrthinger commented on docs/issues-with-!events.md
> +As always, we're here to support you in any way we can, ensuring your Stardew Valley experience is smooth and enjoyable. If you have any further issues or require any assistance, don't hesitate to re
redundant. link to the contact page instead. this will cause an insane amount of drift overtime if we copy this at the end of every help doc.

drift in this case is if we change the email, we're going to have to change it in every article manually.

2024-01-30 09:05 UTC, mrthinger commented on docs/how-to-restart-server.md
> +We understand that occasional bugs can hinder your gameplay, but fret not – we've got a quick and easy solution for you. The best place to start when troubleshooting issues with your Junimohost serve
there is a lot of useless information in this preamble. we can mention that restarting does usually fix most issues, everything else is not helpful.

the context for this doc is the server is already messed up and they want help ASAP, not fluff.

2024-01-30 09:05 UTC, mrthinger commented on docs/how-to-restart-server.md
> +What are the steps? (PC)
(PC) is redundant info, they're visiting a website. this entire line is redundant, you can just list the steps.

2024-01-30 09:05 UTC, mrthinger commented on docs/how-to-restart-server.md
> +If the issue persists, the best way to make us apparent to the issue is to reach out in our Discord server or alternatively contact us at contact@junimohost.com.
same thing as the other file, this is not a good way to maintain up to date contact info. you can just link to the contact page for now.

2024-01-30 09:05 UTC, mrthinger commented on docs/how-to-restart-server.md
> +1. Visit junimohost.com to access your account.
linking to junimohost.com/dashboard will automatically redirect to the login if they arent already logged in, that reduces the first 2 steps down to 1.

2024-01-30 09:05 UTC, mrthinger commented on docs/how-to-restart-server.md
> +3. Once signed in, navigate to the left of the page and locate the 'Restart' button next to the 'Instructions' button, denoted in green.
i think you can remove this entirely and add a picture of where the button is

2024-01-30 09:11 UTC, mrthinger requested changes

2024-01-30 09:11 UTC, mrthinger commented on docs/how-to-restart-server.md
> +# How do I restart my Junimohost Stardew server?
Junimohost should ALWAYS be lowercase
```suggestion
# How do I restart my junimohost Stardew server?
```

2024-02-01 16:23 UTC, Samdaman8 commented on docs/issues-with-!events.md
> +We understand this might cause some inconvenience and are putting measures in place to prevent such occurrences. In the meantime, we appreciate your understanding and cooperation in only entering the
i disagree with you but i reworded it

2024-02-12 23:31 UTC, mrthinger approved these changes

2024-02-12 23:32 UTC, merged